name: Docker Image CI

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '30 17 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push nginx
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
      -
        name: Build and push php-fpm
        uses: docker/build-push-action@v3
        with:
          context: ./php-fpm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:latest
      -
        name: Build and push mosquitto
        uses: docker/build-push-action@v3
        with:
          context: ./mosquitto
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mosquitto:latest
      -
        name: Build and push homeassistant
        uses: docker/build-push-action@v3
        with:
          context: ./homeassistant
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/homeassistant:latest
      -
        name: Build and push unblockneteasemusic
        uses: docker/build-push-action@v3
        with:
          context: ./unblockneteasemusic
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/unblockneteasemusic:latest
      -
        name: Build and push docker-osx-vnc
        uses: docker/build-push-action@v3
        with:
          context: ./docker-osx-vnc
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-osx-vnc:latest
      -
        name: Build and push wechaty
        uses: docker/build-push-action@v3
        with:
          context: ./wechaty
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wechaty:latest
